version: '3'

services:
  db:
    image: spartakode/sqlite3
    volumes:
      - "db-data:/wifiexercise/db.sqlite3"
  web:
    build: .
    command: python wifiexercise/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data: