# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifiId', models.CharField(max_length=256)),
                ('wifiAverageThroughPut', models.FloatField()),
            ],
        ),
    ]
